### ISSUE TITLE
Prix

### ISSUE THREAD

**Issue by chuppito** [jugla/keyatome#26]
Bonjour, je parle en français puisque je suppose que le fait d'avoir créé cette intégration vous êtes français, sinon désolé je changerai de langue.

Le code :
```
template:
  - sensor:
      - name: atome_daily_price
        state: "{{ state_attr('sensor.atome_daily', 'price') | float }}"
        unit_of_measurement: 'EUR'
        state_class: total_increasing
        device_class: monetary
```
Fonctionne très bien et me renvoie un prix. Il va sûrement chercher ce prix dans l'application totalenergie puisque j'ai le même.
Est-ce que ce prix tiens en compte le prix du kWh et de l'abonnement ? Ou juste les kWh ?

Peut on faire le même sensor pour afficher la veille ? Si oui comment ?

Merci d'avance pour l'aide et surtout merci pour cette intégration

**Comment by jugla** [comment]
Bonjour,
oui, j'habite en France ;-) 
En fait, je mets en anglais, comme ca n'importe qui peu suivre.

Le prix est directement donné par TotalEnergies. Cela tient compte des heures pleines/creuses si vous avez ce type d'abonnement !

Dans le senseur vous avez la veille.

```yaml
template:
  - sensor:
      - name: atome_daily_previous_price
        state: "{{ state_attr('sensor.atome_daily', 'previous_price') | float }}"
        unit_of_measurement: 'EUR'
        state_class: total_increasing
        device_class: monetary
```


>>>>>>>>>>>>>>>>>>>>>>>
In english
Hello,
Indeed, I live in France.
I write in english so that everyone can follow.

The price is given by TotalEnergies server. This takes into account peak/offpeak tariff if you have subscribed to this kind of tariff.

In sensor, you have current day and previous one.
So here(above) the yaml code.

**Comment by chuppito** [comment]
Bonsoir, super merci beaucoup.
J'ai modifié votre code pour ajouter le prix de l'abonnement.
Merci pour le code de la veille, plus qu'à trouver une belle carte pour que
je fasse un beau tableau.
Merci beaucoup pour ce keyatome, l'autre ne fonctionne pas chez moi.
Bonne soirée

**Comment by jugla** [comment]
super pour le feedback !

**Comment by chuppito** [comment]
Bonjour, je reviens dessus, est ce qu'il y a le sensor annuel ? Comment avoir le sensor de la veille en kWh ?
Je confirme, celui du prix fonctionne très bien
![Screenshot_20230109-112526](https://user-images.githubusercontent.com/10908251/211287159-f527d1af-282b-4310-928f-8998097a94fc.png)

Il ne me reste plus qu'à trouver mon bonheur dans les cartes github pour embellir 
Merci pour tout

**Comment by jugla** [comment]
Bonjour,
Désolé pour le délai.
Super le coup des billets.
Le senseur annuel a été supprimé car _Total Energies_ ne le fournit plus (depuis la version v7.3.0 de _keyatome_).
Pour avoir la veille en kwh, il y a l'attribut `previous_consumption` pour le senseur `daily` ;-)

**Comment by chuppito** [comment]
Bonjour, merci pour la réponse.
Du coup je suis passé par une carte à la semaine
![Screenshot_20230226-192110](https://user-images.githubusercontent.com/10908251/221429113-a39b5285-9b4b-4bbe-877f-6ce9e954b656.png)

**Comment by jugla** [comment]
Hello,
Je clos l'issue.
Je suis intéressé pour savoir comment tu as fait le graphique : il est joli :-)

**Comment by chuppito** [comment]
Salut, pas de soucis, il y en a 3 à la suite (la photo, puis juste conso et juste prod)

**Comment by chuppito** [comment]
```
type: custom:vertical-stack-in-card
cards:
  - type: custom:apexcharts-card
    graph_span: 7d
    span:
      start: day
      offset: '-7d'
    stacked: false
    header:
      show: true
      title: Achat et vente d'électricité sur 7 jours
    apex_config:
      chart:
        type: area
        height: 400
      stroke:
        show: true
        width: 1
        curve: smooth
      legend:
        show: true
      fill:
        type: gradient
        gradient:
          shadeIntensity: 0.1
          opacityFrom: 0.25
          opacityTo: 1
          inverseColors: true
          stops:
            - 0
            - 50
            - 100
    series:
      - color: rgb(108,218,231)
        entity: sensor.atome_daily_price
        name: Achat d'électricité
        float_precision: 2
        type: column
        group_by:
          func: diff
          duration: 24h
        show:
          datalabels: true
      - color: rgb(163,229,113)
        entity: sensor.vente_surplus_journalier_2
        name: Vente d'électricité
        float_precision: 2
        type: column
        group_by:
          func: diff
          duration: 24h
        show:
          datalabels: true
  - type: custom:apexcharts-card
    graph_span: 7d
    span:
      start: day
      offset: '-7d'
    stacked: true
    header:
      show: true
      title: Achat d'électricité sur 7 jours
    apex_config:
      chart:
        type: area
        height: 400
      stroke:
        show: true
        width: 1
        curve: smooth
      legend:
        show: true
      fill:
        type: gradient
        gradient:
          shadeIntensity: 0.1
          opacityFrom: 0.25
          opacityTo: 1
          inverseColors: true
          stops:
            - 0
            - 50
            - 100
    series:
      - color: rgb(108,218,231)
        entity: sensor.atome_daily_price
        name: Vente d'électricité
        float_precision: 2
        type: column
        group_by:
          func: diff
          duration: 24h
        show:
          datalabels: true
  - type: custom:apexcharts-card
    graph_span: 7d
    span:
      start: day
      offset: '-7d'
    stacked: true
    header:
      show: true
      title: Vente d'électricité sur 7 jours
    apex_config:
      chart:
        type: area
        height: 400
      stroke:
        show: true
        width: 1
        curve: smooth
      legend:
        show: true
      fill:
        type: gradient
        gradient:
          shadeIntensity: 0.1
          opacityFrom: 0.25
          opacityTo: 1
          inverseColors: true
          stops:
            - 0
            - 50
            - 100
    series:
      - color: rgb(163,229,113)
        entity: sensor.vente_surplus_journalier_2
        name: Vente d'électricité
        float_precision: 2
        type: column
        group_by:
          func: diff
          duration: 24h
        show:
          datalabels: true
  - type: custom:bar-card
    severity:
      - color: '#18dc82'
        to: '50'
        from: '0'
      - color: '#97f554'
        from: '26'
        to: '150'
      - color: '#ffff00'
        from: '51'
        to: '500'
    entities:
      - entity: sensor.vente_surplus_an
    icon: mdi:cash-100
```
