### ISSUE TITLE
Price is not reporting corectly

### ISSUE THREAD

**Issue by jcastang** [jugla/keyatome#28]
Hello, 

I have added current price in my energy dashboard using this attribute as increasing cost for energy consumption

- name: sensor.atome_daily_cost
        state: "{{ state_attr('sensor.atome_daily', 'price') | float }}"
        unit_of_measurement: 'euro'
      

But each day it only reports 1.75€ instead of the real price. 

As I login into my Total Énergie account I can see real price. 

Maybe something I misconfigured or misunderstood ?

**Comment by jugla** [comment]
Hello,
Sorry for the delay.
Please if you look directly in HA dashboard the sensor Atome Delay, what is displayed for price and previous price (attributes) ?
Thanks in advance
Philippe

**Comment by jcastang** [comment]
Hello, 
If I look into entities, I see a price for today and previous, but the price is wrong. 
<img width="539" alt="image" src="https://github.com/jugla/keyatome/assets/3185544/ddbfb1b7-97e2-42f0-be61-31d750455c2c">

The real price is near 3/4€

**Comment by jugla** [comment]
I have to correct it

**Comment by jugla** [comment]
Hello,
Please can you check with this template in configuration.yaml : 
````yaml
-template:
  - sensor:
      - name: atome_daily_price
        state: >-
           {% if state_attr('sensor.atome_daily', 'price') == 'unknown' %}
              unknown
           {% else %}
              {{ state_attr('sensor.atome_daily', 'price') }}
           {% endif %}
        #unit_of_measurement: 'EUR'
        state_class: total_increasing
        #device_class: monetary
```
