### ISSUE TITLE
Log error total_increasing can't be used with device class 'monetary'

### ISSUE THREAD

**Issue by ghost** [jugla/keyatome#35]
As the title mentions, I regularly get an error with price entities. See attached a screenshot of the error logged.

<img width="1540" alt="iShot_2024-08-10_08 47 25" src="https://github.com/user-attachments/assets/86434f59-f32f-4c14-b492-9003d577a6cc">

Below the Yaml configuration used:

```
template:
  # Atome Linky Template Montly Tracking
  - sensor:
      - name: Atome Monthly Price
        unique_id: atome_monthly_price
        state: "{{ state_attr('sensor.atome_monthly', 'price') | float }}"
        unit_of_measurement: "EUR"
        state_class: total_increasing
        device_class: monetary
  - sensor:
      - name: Atome Weekly Price
        unique_id: atome_weekly_price
        state: "{{ state_attr('sensor.atome_weekly', 'price') | float }}"
        unit_of_measurement: "EUR"
        state_class: total_increasing
        device_class: monetary
  - sensor:
      - name: Atome Daily Price
        unique_id: atome_daily_price
        state: "{{ state_attr('sensor.atome_daily', 'price') | float }}"
        unit_of_measurement: "EUR"
        state_class: total_increasing
        device_class: monetary
```

**Comment by ghost** [comment]
Update:

I just commented out the device_class line which seems to be legacy from a previous configuration and it solved the issue.

```
  - sensor:
      - name: Atome Monthly Price
        unique_id: atome_monthly_price
        state: "{{ state_attr('sensor.atome_monthly', 'price') | float }}"
        unit_of_measurement: "EUR"
        state_class: total_increasing
        #device_class: monetary
```
