### ISSUE TITLE
Sensor costs showing unknown value

### ISSUE THREAD

**Issue by milescherif** [jugla/keyatome#4]
**Describe the bug**

I had 2 problems with atome :
- Can't update data after 2 hours
- Sensor costs showing unknown value

I stopped using native atome and installed keyatome. Update data has been resolved, many thanks for your great work !
Then, I still have a problem with sensor costs. I don't know what I'm doing wrong, do I need to edit my configuration.yaml ?

**To Reproduce**
1. Add the entity "sensor.atome_daily_cost" on dashboard
It's been a week now.

**Expected behavior**
I'm waiting for the value in €.

**Screenshots**
[Link](https://ibb.co/PtpFwL4) of my screenshot (dashboard).

**Desktop (please complete the following information):**
 - OS: Raspberry pi 4 with Home assistant operating system
 - Browser : Chrome, Safari
 - Version HA : 2021.12.7
 - Version Core : core-2021.12.7

**Comment by jugla** [comment]
Thanks a lot for your feed back !
`sensor.atome_daily_cost` is not a sensor generated by `atome` or `keyatome` integration.
`sensor.atome_daily` contains attribute `price`
Hereafter an example (with the `keyatome` integration) : 
![image](https://user-images.githubusercontent.com/59493499/148694292-f495ca52-02b8-47b8-a623-d8ac71094dad.png)
NB : I've performed some test with UI, that's why there are some hole in the curve

**Comment by jugla** [comment]
Here something that you can try, if you want the `sensor.atome_daily_cost`  : 
In `configuration.yaml` , perform the following declaration : 
```yaml
template:
  - sensor:
      - name: atome_daily_cost
        state: "{{ state_attr('sensor.atome_daily', 'price') | float }}"
        unit_of_measurement: 'euro'
```

with snapshot
![image](https://user-images.githubusercontent.com/59493499/148694865-157903ef-5d59-4880-bd0c-4aafa44fbb8d.png)

**Comment by milescherif** [comment]
Ok fine ! I didn't see that `sensor.atome_daily` contains the value. It's now working ! Great job, many thanks again 🥇 

[Here the result](https://ibb.co/yntYN3J).

I added the other ones : 

```
template:
  - sensor:
      - name: sensor.atome_daily_cost
        state: "{{ state_attr('sensor.atome_daily', 'price') | float }}"
        unit_of_measurement: 'euro'
      
      - name: sensor.atome_weekly_cost
        state: "{{ state_attr('sensor.atome_weekly', 'price') | float }}"
        unit_of_measurement: 'euro'
      
      - name: sensor.atome_monthly_cost
        state: "{{ state_attr('sensor.atome_monthly', 'price') | float }}"
        unit_of_measurement: 'euro'
```
